[Http]
Port = ":8084"

[Mysql]
Host     = "localhost"
Port     = 3306
User     = "root"
Password = "123123"
Database = "kolesa_web_bot"

[Bot]
Token     = "452924814:AAGm-gvvr0wZ8pEVaj1g6lYvUvyO8-TxJQc"
Timeout   = 60
StartPic  = "AgADBAAD32E7G5oYZAdr8YAdPxCre1lRJhoABIBL2MbyjNBBXvAAAgI"
ChannelId = "-1001215668907"